### ISSUE TITLE
投稿系の投稿先グループが多くなる可能性が高いので、プルダウン化

### ISSUE THREAD

**Issue by Teityan** [Actlogy/Aclass#21]
うちの学校の場合、各クラスごとのクラス(GoogleClassroomの)と教科別のクラスが作られていることを考えると、プルダウンにした方がいい気がする。
うちの場合は部活動も含め約20クラスある(一クラスあたり)
そんなに難しくないので、自分が担当します。

**Comment by Teityan** [comment]
ちょっと待った
複数同時投稿が出来なくなるな

**Comment by Teityan** [comment]
とりあえず、この話はなしだな

**Comment by asuchi0819** [comment]
select タグの multiple 属性を指定すれば、複数選択は可能。
[参考 - MDN](https://developer.mozilla.org/ja/docs/Web/HTML/Element/select)
> **multiple**
真偽値属性で、リストの複数の選択肢を選択することができることを示します。指定されていない場合は、一度に選択することができる選択肢は一つだけです。 multiple が指定されている場合、多くのブラウザーは単一行のドロップダウンの代わりに、スクロールするリストボックスを表示します。

対応状況を見ても、multiple属性でよい気はする。

その以外の方法だと、一つプルダウンを選択したらもう一つ空のプルダウンを横か縦に足すことで、複数同時投稿はできそう。
