### ISSUE TITLE
ログインページの作成

### ISSUE THREAD

**Issue by asuchi0819** [Actlogy/Aclass#5]
ログインページの作成をお願いします。
基本は、「 resources / views / auth / login.blade.php 」です。
ただ、テンプレートとして「 resources / views / layouts / app.blade.php 」を用いているので、「 resources / views / layouts / auth.blade.php 」にコピー後そちらの修正もお願いします。

- Vue.jsやBootstrapを使わないことによる、デザインを含めたコードの修正。
- ログイン時の識別子をemailからlogin_idへ変更
- reCAPTCHA v2の搭載（[https://github.com/anhskohbo/no-captcha](https://github.com/anhskohbo/no-captcha)）

**Comment by kai0310** [comment]
こちら私が担当します
